# Generated by Django 5.0.1 on 2024-01-25 11:11

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_cart_session_id_alter_cart_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=200, null=True),
        ),
    ]
