# Generated by Django 5.0.1 on 2024-01-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_order_shipping_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default=False, max_length=254),
            preserve_default=False,
        ),
    ]
