# Generated by Django 5.0.1 on 2024-02-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0020_alter_order_shipping_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="first_name",
            field=models.CharField(default=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="last_name",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
